apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-efs-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-1234567 # this should be your FS ID for EFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-efs-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 25Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
  annotations:
    # see https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/ for additional annotations
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /index.php
    alb.ingress.kubernetes.io/success-codes: 200,201,302
  labels:
    app: wordpress-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: wordpress-service
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  spec:
    containers:
      - image: wordpress:5.3-apache
        name: wordpress
        env:
          - name: WORDPRESS_DB_HOST
            value: wordpress-db.cluster-123456789.us-east-1.rds.amazonaws.com # URL to your RDS instance
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: admin
          - name: WORDPRESS_DB_PASSWORD
            value: supersecretpassword # I recommend saving these in kubernetes secrets
        ports:
        - containerPort: 80
        volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html/wp-content/uploads
      volumes:
        - name: wordpress-efs-uploads
          persistentVolumeClaim:
            claimName: wordpress-efs-uploads-pvc
